### PR TITLE
Strip script tags to prevent xss.

### PR DESCRIPTION
**Pull request by thepug**
This change removes tags that are problems when displaying in a web browser.

To test:

Use postman to make a request to the storage service.
- copy the header information from a succesful post creation (Content-Type, Authorization, etc)
- copy the body from the succesful post
- in postman use the same body but add a `<script> alert('wtf'); </script>` or `<style>lfjd</style>` tag in the body or headline.
- [x] the returned request should show the tags removd
- [x] query the database to see that the tags are not stored

- Repeat the same steps for board creation
- change the name to include the `<script>` or `<style>` tags
- [x] are the tags removed?

- Repeat the same steps for invites 
- add a note field with the tags
- [x] are they removed?

### CODE REVIEW

**Comment by thepug** [comment]
[XSS in UCG fields](https://trello.com/c/OcksUdyb/1527-xss-in-ucg-fields)

**Comment by bago2k4** [comment]
@thepug i have this in email:
```
Message ( invite ) from SQS: {:type "invite", :first-name "", :note "<script>alert('malicious goes here');</script>", :from-avatar "https://cdn.filestackcontent.com/5bNHjarQQKLmLSifqRXa", :from "Iacopo Carraro", :org-name "11 October 5", :org-logo-width 0, :reply-to "bago2k4+11Oct5@gmail.com", :token-link "http://localhost:3559/invite?token=6a60210f-89aa-4c0b-9657-96f0ad8a2c5c", :org-logo-url "", :org-logo-height 0, :to "bago2k4+11OctA1@gmail.com"}
```
I invited a user and added that script tag in the note field, sent via cURL:
```
curl -i \
 -H "Access-Control-Allow-Headers: Content-Type, Authorization" \
 -H "Accept: application/vnd.open-company.user.v1+json" \
 -H "Authorization: Bearer YOUR_JWT_HERE" \
-H "Content-Type: application/vnd.open-company.team.invite.v1" \
-X POST -d @/path/to/payload.json \
http://localhost:3003/teams/4264-4cea-876d/users/
```

/path/to/payload.json is:
```
{"admin": false,
"email": "bago2k4+11OctA1@gmail.com",
"first-name": "",
"last-name": "",
"logo-height": 0,
"logo-url": null,
"logo-width": 0,
"note": "<script>alert('malicious goes here');</script>",
"org-name": "11 October 5"}
```

**Comment by thepug** [comment]
@bago2k4 https://github.com/open-company/open-company-storage/pull/158#issuecomment-429079097   this is intended.  The email shouldn't contain the script tag. I don't strip the sqs message of the data.

**Comment by bago2k4** [comment]
Seems like emails still have the script and style tags inside even if they are not visible because email clients hide them.

**Comment by bago2k4** [comment]
@thepug i still see malicious code in the email logs, there are 2 cases here:
1) invite to private board
2) invite to team

1) is solved, i get the email and i see the text that was inside the script/style tag because it was stripped out of it

2) is not, i get empty note because the email has the HTML markup still in the note field.

**Comment by thepug** [comment]
@bago2k4 I believe this,https://github.com/open-company/open-company-storage/pull/158#issuecomment-429526298,  is all the auth service and should be moved to that PR 
https://github.com/open-company/open-company-auth/pull/61

Are you using that branch?  Any requests to port 3003 is auth service. 3001 is the storage service and relates to this PR.

**Comment by Ferossgp** [comment]
There is also a risk of XSS in other HTML tags like `<input type="text" value="" onfocus="alert(1)" autofocus="" />` and this is also sent to email in header only with difference that email client removes XSS from input.

**Comment by thepug** [comment]
@Ferossgp thanks for this https://github.com/open-company/open-company-storage/pull/158#issuecomment-429786052.  I'll make sure to add these tags that support things like onfocus and other ways to execute javascript.

**Comment by bago2k4** [comment]
@thepug invite to private section strip out everything but not the input field, for this note input:
```
<script>This is inside script</script> and <style>This is inside style</style> and <input value\"this is inside an input\" autofocus=\"autofocus\" /> and this is out
```
i get this in email
```
This is inside script and this is inside style and <input value=\\\"this is inside an input\\\" autofocus=\\\"autofocus\\\" /> this is out
```
and i see this

**Comment by bago2k4** [comment]
Works

**Pull request merged**
