### PR TITLE
Post sorting

### PR DESCRIPTION
**Pull request by bago2k4**
Main PR: https://github.com/open-company/open-company-web/pull/911

### CODE REVIEW

**Comment by bago2k4** [comment]
[Sort and filter posts](https://trello.com/c/CJahkpWQ/1992-sort-and-filter-posts)

**Comment by belucid** [comment]
@bago2k4 CI failing here.

**Comment by belucid** [comment]
@bago2k4 conflicts here.

**Comment by bago2k4** [comment]
@belucid solved

**Comment by belucid** [comment]
@bago2k4 Let's normalize the new/updated URLs a bit:

**AP:**

Recently posted
`../entries`

Recent activity
`../activity`

**Boards:**

Recently posted
`../entries`

Recent activity
`../activity`

So then, future, we'll stay consistent with people too:

Recently posted
`/orgs/:org-slug/person/:user-uuid/entries`

Recent activity
`/orgs/:org-slug/person/:user-uuid/activity`

**Pull request merged**
