### PR TITLE
Fix viewer contributor access

### PR DESCRIPTION
**Pull request by bago2k4**
Bug: if you setup a viewer with author access to a private section you will see that:
- no edit/delete entry links are sent (at least on AP api)
- publish is not allowed (create post and save are though)
- share is not allowed
- drafts board is not present

To test:
- with user A that is an admin of the org
- add a viewer (user B) to your org
- add 2 private sections (section 1 and section 2)
- make the viewer an author on Section 1 only
- with user A
- make sure you get edit/delete links in the menu in All posts for activities on all boards
- make sure you get edit/delete links in the menu in section 1 and section 2
- with user B
- go to All posts
- make sure you get Share only for team sections
- make sure you get edit/delete links for Section 1
- make sure you get only share for Section 2 posts
- now go to Section 1
- make sure you get edit/delete
- now go to Section 2
- make sure you get only share
- make sure user B sees drafts board
- make sure you can create posts only in Section 1
- make sure you can move posts only to Section 1
- make sure you can remind a use of a post in Section 1

### CODE REVIEW

**Comment by bago2k4** [comment]
@belucid wait to merge this, in this case i still get a 403:
- add a public section
- use a viewer user
- try to remind a Slack user with the viewer
- 💥 403
- it works if you try it for a post in a private section where the viewer is author

this makes sense, the viewer is not allowed to write that resource, even if it's in a public section it's not writable by a viewer of the org...

**Comment by bago2k4** [comment]
[Viewer w/ contributor access in private sections](https://trello.com/c/D83rot4i/2075-viewer-w-contributor-access-in-private-sections)

**Comment by belucid** [comment]
@bago2k4 

Not sure I get this test item, "make sure you get Share only for team sections"

A/ it doesn't happen, I get share on all items
B/ not sure it shouldn't happen, do we have a requirement not to get share on private sections?

**Comment by belucid** [comment]
@bago2k4 

As a viewer I don't get the ... ellipse FoC to handle mark as read/unread. Is that in another branch maybe?

**Comment by belucid** [comment]
@bago2k4 

As viewer user B I get the "Create a new post" button in empty sections that I'm not a contributor in.

**Comment by belucid** [comment]
@bago2k4 

"make sure you can remind a use of a post in Section 1"

Assign to just spins forever as User B.

**Comment by bago2k4** [comment]
@belucid about this:
> Not sure I get this test item, "make sure you get Share only for team sections"
So this item is a mistake, ignore it. The good one is this:
> make sure you get only share for Section 2 posts

But that's also not right anymore. Before share to Slack required to write to the entry but now the share is only via url so it's ok, ignore those.

About this:
> As a viewer I don't get the ... ellipse FoC to handle mark as read/unread. Is that in another branch maybe?
That's in `fast-copy-changes` of web

Finally about this:
> make sure you can remind a use of a post in Section 1

I found a bug that has probably been around from a long time (2 years actually), a typo: `:viemer` instead of `:viewer` and that was causing viewers to get boards w/o authors and viewers list. This cause issues in WRT.

**Pull request merged**
