### PR TITLE
Handle auto share on video processing.

### PR DESCRIPTION
**Pull request by thepug**
Needs: https://github.com/open-company/open-company-auth/pull/55

This change waits for a video to be processed before doing the slack auto share.

To test:
- Create a section that auto shares to slack for all posts.
- create a non-video post in this section
- [x] Did the post get shared to slack?

- Create a video post in the same section
- [x] does that post not get shared immediately (or if the video is still being processed)?
- [x] Does the post get shared when the video is done processing?

### CODE REVIEW

**Comment by thepug** [comment]
[send to the bot once the video is ready rather than on publish, so users don't look until it's time](https://trello.com/c/zVJecrbY/1460-send-to-the-bot-once-the-video-is-ready-rather-than-on-publish-so-users-dont-look-until-its-time)

**Comment by bago2k4** [comment]
@thepug and @belucid maybe the magic token stuff should be moved to lib, that stuff is probably useful in other services, WYT?

magic token is how Nathan called the piece of code that request for a JWT to Auth service given a user UUID.

**Comment by bago2k4** [comment]
Not sure if this helps, this is the board map:
```
{
"access":  "team" ,
"author": {
"avatar-url": https://avatars.slack-edge.com/2017-02-02/136114833346_3758034af26a3b4998f4_512.jpg, »
"name":  "Iacopo Carraro" ,
"user-id":  "a2bc-45d2-9364"
} ,
"authors": [
"a2bc-45d2-9364"
] ,
"created-at":  "2018-09-03T13:38:46.820Z" ,
"draft": false ,
"name":  "Aux" ,
"org-uuid":  "7629-4ede-993d" ,
"slack-mirror": {
"channel-id":  "C09LQRMQX" ,
"channel-name":  "test-channel" ,
"slack-org-id":  "T06SBMH60"
} ,
"slug":  "aux" ,
"updated-at":  "2018-09-03T13:38:46.820Z" ,
"uuid":  "eb66-4b7f-b33d" ,
"viewers": [ ]
}
```

**Comment by bago2k4** [comment]
Between this is not a one time thing, i tried before w/o cleaning the DB and it shared all the non video entries, but not the ones with a video. Then i cleaned the DB and restarted all the services, no luck.

**Comment by thepug** [comment]
@bago2k4 I'm able to auto share a video after processing. https://opencompanyhq.slack.com/archives/C09LQRMQX/p1536066617000100

It is probably best to share the storage service logs instead of the bot logs.  Although if the bot is receiving the message to share, that should be fine.

Maybe post both service's logs?

**Comment by belucid** [comment]
Where are we at with this one @thepug and @bago2k4 ?

**Comment by thepug** [comment]
>Where are we at with this one @thepug and @bago2k4 ?

@belucid Go through the QA steps to see if you can repeat @bago2k4's issue.

**Comment by thepug** [comment]
Only share on `:video-processed` change from false to true.  This should prevent multiple shares.

There is a version exception being thrown that needs to be fixed. Either skip the version insert or property increment the version number.

**Comment by belucid** [comment]
@thepug 

So findings... missing Bot posting seems related to gaps in docs. Those are resolved.

- Version increment exception
- Double auto-share ("Video Post Test" and "Video Post Test 4" in #bot-testing) with longer videos (a few minutes +)

**Comment by thepug** [comment]
double share has been addressed.

So for the version increment exception, this should only be happening on a publish and is unrelated to the video code.  The versions are only created on post creation and post publish.  You should be able to recreate this by publishing a non-video post.  We should probably open a trello card for this on. I need to also see if it is fixed it the `auto-save` branch.

**Pull request merged**
